spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'gimyongjun414@gmail.com'
    password: 'uaae kceo ihwr croz'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false
    username: root
    password: 1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kyj.*
  configuration:
    map-underscore-to-camel-case: true

s3:
  credentials:
    access-key: ''
    secret-key: ''
    region: ap-northeast-2
    bucket: ''

logging:
  level:
    jdbc.sqltiming: DEBUG       # SQL + 파라미터 + 실행 시간
    jdbc.resultsettable: DEBUG  # 쿼리 결과 컬럼값
    jdbc.sqlonly: OFF
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.connection: OFF
